#include "DescriptorHeap.h"

using namespace Engine;

D3D12_DESCRIPTOR_HEAP_TYPE DescriptorHeap::DescHeapType[] =
{
	D3D12_DESCRIPTOR_HEAP_TYPE_RTV,
	D3D12_DESCRIPTOR_HEAP_TYPE_DSV,
	D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV
};