#include "QueryHeap.h"

using namespace Engine;

D3D12_QUERY_HEAP_TYPE QueryHeap::TypeD3D[] =
{
	D3D12_QUERY_HEAP_TYPE_OCCLUSION,
	D3D12_QUERY_HEAP_TYPE_PIPELINE_STATISTICS,
	D3D12_QUERY_HEAP_TYPE_SO_STATISTICS,
	D3D12_QUERY_HEAP_TYPE_TIMESTAMP
};